version: "3.3"

services:
    poemonitor:
        deploy:
            mode: replicated
            replicas: 1
        networks:
            - poemonitor-network
        build:
            context: '.'
            dockerfile: Dockerfile-poemonitor
        volumes:
            - "/storage/misc/repository/poemonitor-ioc/src/ioc:/usr/local/poemonitor-ioc/"
        logging:
            driver: "json-file"
            options:
                max-file: 10
                max-size: 10m

networks:
    poemonitor-network:
        external:
            name: "host"
