version: "3.3"

services:
    ioc:
        deploy:
            mode: replicated
            replicas: 1
	    placement:
	       constraints:
	       - node.hostname == CA-RaCtrl-CO-Srv-1
        networks:
            - poemonitor-network
        image: lnlscon/poemonitor:v1.0
        volumes:
            - "/storage/misc/repository/poemonitor-ioc/src/ioc/withoutApiLogin:/usr/local/poemonitor-ioc"
        logging:
            driver: "json-file"
            options:
                max-file: 10
                max-size: 10m

networks:
    poemonitor-network:
        external:
            name: "host"
